[dev]
framework = "#static"
command = "npx @11ty/eleventy --quiet --watch"

[build]
command = "npx @11ty/eleventy"
publish = "_site"

[[edge_functions]]
function = "tipr"
path = "/process/"

[[edge_functions]]
function = "reset"
path = "/*"

[[edge_functions]]
function = "eleventy-edge"
path = "/*"

[[headers]]
  for = "*"
  [headers.values]
  Content-Security-Policy = "default-src 'self' data: 'unsafe-inline'; upgrade-insecure-requests; block-all-mixed-content; disown-opener"
  Report-To = '{"group":"default","max_age":31536000,"endpoints":[{"url":"https://aarongustafson.report-uri.com/a/d/g"}],"include_subdomains":true}'
  Timing-Allow-Origin = "*"
  Upgrade-Insecure-Requests = "1"
  X-Content-Type-Options = "nosniff"
  X-UA-Compatible = "ie=edge,chrome=1"
  X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*.html"
  [headers.values]
  Link = [
  "</serviceworker.js>;as=script;rel=preload",
  ]

[[headers]]
  for = "/serviceworker.js"
  [headers.values]
  Cache-Control = "max-age=0"
