[dev]
framework = "#static"
command = "npx @11ty/eleventy --quiet --watch"

[build]
command = "npx @11ty/eleventy"
publish = "_site"

[[edge_functions]]
function = "tipr"
path = "/process/"

[[edge_functions]]
function = "reset"
path = "/*"

[[edge_functions]]
function = "eleventy-edge"
path = "/*"
